AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "App Runner SQS integration with Lambda"

Globals:
  Function:
    Timeout: 120

Resources:
  SQSFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: SQSFunction
      Handler: io.pomatti.lambda.Function::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      MemorySize: 1024
      Environment:
        Variables:
          APP_RUNNER_URL: ""
          APP_RUNNER_USERNAME: ""
          APP_RUNNER_SECRET_MANAGER_PASSWORD: ""
